---
- tap:
    - chanzuckerberg/tap
    - github/gh
    - homebrew/cask
    - homebrew/cask-versions
    - homebrew/core
    - homebrew/services
    - mongodb/brew
    - twilio/brew

- brew:
  - ctags
  - desk
  - jpeg
  - libtiff
  - webp
  - ghi
  - git
  - gmailctl
  - pinentry
  - go
  - gopass
  - python
  - graphviz
  - hashcat
  - hub
  - hugo
  - little-cms2
  - libxml2
  - node
  - jq
  - jsonnet
  - libmagic
  - mas
  - nmap
  - p7zip
  - pinentry-mac
  - pipx
  - pyenv
  - ruby-build
  - rbenv
  - reattach-to-user-namespace
  - shellcheck
  - sipcalc
  - speedtest-cli
  - terraform
  - terraform-docs
  - terraformer
  - the_silver_searcher
  - tmate
  - tmux
  - travis
  - tree
  - wakatime-cli
  - wget
  - zlib
  - zsh
  - chanzuckerberg/tap/fogg
  - github/gh/gh
  - mongodb/brew/mongodb-community
  - twilio/brew/twilio

- cask:
  - 1password
  - 1password-cli
  - adobe-creative-cloud
  - adoptopenjdk
  - aerial
  - alfred
  - authy
  - barrier
  - basecamp
  - cheatsheet
  - dash
  - discord
  - docker
  - docker-toolbox
  - dotnet-sdk
  - dropbox
  - fantastical
  - firefox
  - firefox-developer-edition
  - franz
  - github
  - google-chrome
  - hey
  - iterm2
  - jetbrains-toolbox
  - joplin
  - keybase
  - kitematic
  - microsoft-office-2016
  - mindforger
  - mono-mdk-for-visual-studio
  - ngrok
  - notion
  - obs
  - obs-virtualcam
  - omnigraffle
  - openlp
  - parallels
  - powershell
  - protonvpn
  - rectangle
  - screens
  - scrivener
  - setapp
  - signal
  - slack
  - spotify
  - teamviewer
  - tower2
  - transmit
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio
  - visual-studio-code
  - vlc
  - vmware-fusion
  - whatsapp
  - wireshark
  - yt-music
  - zoomus