#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.dotfiles/shell/zsh/config/*.zsh) source $config_file

# Created by `userpath` on 2020-01-08 02:10:19
export PATH="$PATH:/Users/joel/.local/bin"
export GPG_TTY=$(tty)
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# added by travis gem
[ -f /Users/joel/.travis/travis.sh ] && source /Users/joel/.travis/travis.sh

source <("/usr/local/bin/starship" init zsh --print-full-init)
