- link:
    ~/.asdfrc: tools/asdf/asdfrc

- asdf:
  - plugin: go
    url: https://github.com/kennyp/asdf-golang
  - plugin: python
    global: 3.8.3
    versions:
      - 3.8.3
  - plugin: ruby
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git
