- link:
    ~/Brewfile: tools/homebrew/Brewfile
    /usr/local/bin/brewup: tools/homebrew/brewup

- tap:
  - github/gh
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts   
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - mongodb/brew
  - twilio/brew

- brew:
  - asdf
  - ctags
  - gh
  - ghq
  - git
  - git-lfs
  - gnupg
  - gopass
  - htop
  - jpeg
  - jq
  - libmagic
  - libtiff
  - libxml2
  - mas
  - p7zip
  - pinentry
  - pinentry-mac
  - travis
  - webp
  - wget
  - zlib
  - zsh

- cask:
  - visual-studio-code

- shell:
  - [brewup, Updating Homebrew and installed programs]