- create:
  - ~/.zsh.before
  - ~/.zsh.after
  - ~/.secrets


- link:
    ~/.zprezto: shells/zsh/prezto
    ~/.zlogin: shells/zsh/zlogin
    ~/.zlogout: shells/zsh/zlogout
    ~/.zpreztorc: shells/zsh/zpreztorc
    ~/.zprofile: shells/zsh/zprofile
    ~/.zshenv: shells/zsh/zshenv
    ~/.zshrc: shells/zsh/zshrc
    ~/.zmodules: shells/zsh/modules
    ~/.config/starship.toml: shells/starship/starship.toml
