- create:
  - ~/.zsh.before
  - ~/.zsh.after
  - ~/.secrets
  

- link:
    ~/.zprezto: shell/zsh/prezto
    ~/.zlogin: shell/zsh/zlogin
    ~/.zlogout: shell/zsh/zlogout
    ~/.zpreztorc: shell/zsh/zpreztorc
    ~/.zprofile: shell/zsh/zprofile
    ~/.zshenv: shell/zsh/zshenv
    ~/.zshrc: shell/zsh/zshrc
    ~/.zmodules: shell/zsh/modules
    ~/.config/starship.toml: shells/starship/starship.toml
  